[build]
  # Build command to run
  command = "npm run build:client"
  
  # Directory to publish (where the built files are)
  publish = "dist/public"
  
  # Base directory for the build
  base = "."

[build.environment]
  # Node version
  NODE_VERSION = "18"

# Redirect all API calls to your backend server
[[redirects]]
  from = "/api/*"
  to = "https://your-backend-name.onrender.com/api/:splat"
  status = 200
  force = true

# Handle client-side routing (SPA)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' data:; connect-src 'self' https:;"

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache images
[[headers]]
  for = "*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=86400"

[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "public, max-age=86400"

[[headers]]
  for = "*.webp"
  [headers.values]
    Cache-Control = "public, max-age=86400"